version: '3.1'

services:

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: azerty-85
      MYSQL_DATABASE: thegoatencryptor
    restart: on-failure
    volumes:
      - /var/adonis:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080